version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: gunicorn double_codification.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  static_volume:
  postgres_data:

networks:
  app_network:
    driver: bridge
